apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app1-deploy
  name: app1-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app1-deploy
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}

